#在默认设置下，Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为。
#禁止方式如下：在application.properties配置文件中增加以下内容
server:
  port: 8083

eureka:
  client.register-with-eureka: false
  client.fetch-registry: false

spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ShanghaoEnomatic?autoReconnect=true&useSSL=false&characterEncoding=utf-8
      username: root
      password: 123456mn
      #阿里数据库连接池
      type: com.alibaba.druid.pool.DruidDataSource
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 1
      minIdle: 3
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  redis:
      host: 127.0.0.1
      #redis密码，没有密码的可以用～表示
      password: 123456mn
      port: 6379
      pool:
        max-active: 100
        max-idle: 10
        max-wait: 100000
mybatis:
  mapper-locations: classpath:/mapper/**.xml

#配置log路径
logging:
    path: ./
    file: shirodemo.log


